---
- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure node_exporter extra options
  ansible.builtin.copy:
    dest: /etc/default/prometheus-node-exporter
    mode: "0644"
    content: |
      ARGS="--web.listen-address=:{{ node_exporter_port }} --collector.systemd --collector.processes"
  notify: Restart node_exporter

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
