---
name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Install Ansible collections
        run: uvx --with ansible ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: uvx ansible-lint --fix
